{"metadata": {"dbt_schema_version": "https://schemas.getdbt.com/dbt/sources/v3.json", "dbt_version": "1.7.13", "generated_at": "2024-04-25T19:07:25.391063Z", "invocation_id": "15682bb9-a569-4a5d-8222-7192be0e9c6c", "env": {}}, "results": [{"unique_id": "source.dbtjanpro2.jaffle_shop.customers", "error": "Database Error in source customers (models\\staging\\jaffle_shop\\src_jaffle_shop.yml)\n  000904 (42000): SQL compilation error: error line 2 at position 10\n  invalid identifier '_ETL_LOADED_AT'", "status": "runtime error"}, {"unique_id": "source.dbtjanpro2.jaffle_shop.orders", "max_loaded_at": "2024-04-25T05:59:48.365000+00:00", "snapshotted_at": "2024-04-25T19:07:24.026000+00:00", "max_loaded_at_time_ago_in_s": 47255.661, "status": "pass", "criteria": {"warn_after": {"count": 90, "period": "day"}, "error_after": {"count": 100, "period": "day"}, "filter": "datediff('day', _etl_loaded_at, current_timestamp) < 2"}, "adapter_response": {"_message": "SUCCESS 1", "code": "SUCCESS", "rows_affected": 1, "query_id": "01b3e93b-0105-1b16-0005-68570003009e"}, "timing": [{"name": "compile", "started_at": "2024-04-25T19:07:24.090668Z", "completed_at": "2024-04-25T19:07:24.090668Z"}, {"name": "execute", "started_at": "2024-04-25T19:07:24.102681Z", "completed_at": "2024-04-25T19:07:25.380105Z"}], "thread_id": "Thread-2 (worker)", "execution_time": 1.2963941097259521}], "elapsed_time": 2.4642486572265625}